name: Tests

on:
  push:
    branches:
      - main
  create:
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # Run every 1st of the month at 7:42am UTC.
    - cron:  '42 7 1 * *'

jobs:
  benchopt_dev:
    uses: benchopt/template_benchmark/.github/workflows/test_benchmarks.yml@main
    with:
      benchmark_dir: benchmark
      benchopt_branch: benchopt@main
  benchopt_release:
    uses: benchopt/template_benchmark/.github/workflows/test_benchmarks.yml@main
    with:
      benchmark_dir: benchmark
      benchopt_version: latest
